const districts = [
  {
    districtId: '001',
    name: 'Quận Ba Đình',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '002',
    name: 'Quận Hoàn Kiếm',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '003',
    name: 'Quận Tây Hồ',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '004',
    name: 'Quận Long Biên',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '005',
    name: 'Quận Cầu Giấy',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '006',
    name: 'Quận Đống Đa',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '007',
    name: 'Quận Hai Bà Trưng',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '008',
    name: 'Quận Hoàng Mai',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '009',
    name: 'Quận Thanh Xuân',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '016',
    name: 'Huyện Sóc Sơn',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '017',
    name: 'Huyện Đông Anh',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '018',
    name: 'Huyện Gia Lâm',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '019',
    name: 'Quận Nam Từ Liêm',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '020',
    name: 'Huyện Thanh Trì',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '021',
    name: 'Quận Bắc Từ Liêm',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '024',
    name: 'Thành phố Hà Giang',
    type: 'Thành phố',
    provinceId: '02',
  },
  {
    districtId: '026',
    name: 'Huyện Đồng Văn',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '027',
    name: 'Huyện Mèo Vạc',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '028',
    name: 'Huyện Yên Minh',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '029',
    name: 'Huyện Quản Bạ',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '030',
    name: 'Huyện Vị Xuyên',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '031',
    name: 'Huyện Bắc Mê',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '032',
    name: 'Huyện Hoàng Su Phì',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '033',
    name: 'Huyện Xín Mần',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '034',
    name: 'Huyện Bắc Quang',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '035',
    name: 'Huyện Quang Bình',
    type: 'Huyện',
    provinceId: '02',
  },
  {
    districtId: '040',
    name: 'Thành phố Cao Bằng',
    type: 'Thành phố',
    provinceId: '04',
  },
  {
    districtId: '042',
    name: 'Huyện Bảo Lâm',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '043',
    name: 'Huyện Bảo Lạc',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '044',
    name: 'Huyện Thông Nông',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '045',
    name: 'Huyện Hà Quảng',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '046',
    name: 'Huyện Trà Lĩnh',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '047',
    name: 'Huyện Trùng Khánh',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '048',
    name: 'Huyện Hạ Lang',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '049',
    name: 'Huyện Quảng Uyên',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '050',
    name: 'Huyện Phục Hoà',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '051',
    name: 'Huyện Hoà An',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '052',
    name: 'Huyện Nguyên Bình',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '053',
    name: 'Huyện Thạch An',
    type: 'Huyện',
    provinceId: '04',
  },
  {
    districtId: '058',
    name: 'Thành Phố Bắc Kạn',
    type: 'Thành phố',
    provinceId: '06',
  },
  {
    districtId: '060',
    name: 'Huyện Pác Nặm',
    type: 'Huyện',
    provinceId: '06',
  },
  {
    districtId: '061',
    name: 'Huyện Ba Bể',
    type: 'Huyện',
    provinceId: '06',
  },
  {
    districtId: '062',
    name: 'Huyện Ngân Sơn',
    type: 'Huyện',
    provinceId: '06',
  },
  {
    districtId: '063',
    name: 'Huyện Bạch Thông',
    type: 'Huyện',
    provinceId: '06',
  },
  {
    districtId: '064',
    name: 'Huyện Chợ Đồn',
    type: 'Huyện',
    provinceId: '06',
  },
  {
    districtId: '065',
    name: 'Huyện Chợ Mới',
    type: 'Huyện',
    provinceId: '06',
  },
  {
    districtId: '066',
    name: 'Huyện Na Rì',
    type: 'Huyện',
    provinceId: '06',
  },
  {
    districtId: '070',
    name: 'Thành phố Tuyên Quang',
    type: 'Thành phố',
    provinceId: '08',
  },
  {
    districtId: '071',
    name: 'Huyện Lâm Bình',
    type: 'Huyện',
    provinceId: '08',
  },
  {
    districtId: '072',
    name: 'Huyện Nà Hang',
    type: 'Huyện',
    provinceId: '08',
  },
  {
    districtId: '073',
    name: 'Huyện Chiêm Hóa',
    type: 'Huyện',
    provinceId: '08',
  },
  {
    districtId: '074',
    name: 'Huyện Hàm Yên',
    type: 'Huyện',
    provinceId: '08',
  },
  {
    districtId: '075',
    name: 'Huyện Yên Sơn',
    type: 'Huyện',
    provinceId: '08',
  },
  {
    districtId: '076',
    name: 'Huyện Sơn Dương',
    type: 'Huyện',
    provinceId: '08',
  },
  {
    districtId: '080',
    name: 'Thành phố Lào Cai',
    type: 'Thành phố',
    provinceId: '10',
  },
  {
    districtId: '082',
    name: 'Huyện Bát Xát',
    type: 'Huyện',
    provinceId: '10',
  },
  {
    districtId: '083',
    name: 'Huyện Mường Khương',
    type: 'Huyện',
    provinceId: '10',
  },
  {
    districtId: '084',
    name: 'Huyện Si Ma Cai',
    type: 'Huyện',
    provinceId: '10',
  },
  {
    districtId: '085',
    name: 'Huyện Bắc Hà',
    type: 'Huyện',
    provinceId: '10',
  },
  {
    districtId: '086',
    name: 'Huyện Bảo Thắng',
    type: 'Huyện',
    provinceId: '10',
  },
  {
    districtId: '087',
    name: 'Huyện Bảo Yên',
    type: 'Huyện',
    provinceId: '10',
  },
  {
    districtId: '088',
    name: 'Huyện Sa Pa',
    type: 'Huyện',
    provinceId: '10',
  },
  {
    districtId: '089',
    name: 'Huyện Văn Bàn',
    type: 'Huyện',
    provinceId: '10',
  },
  {
    districtId: '094',
    name: 'Thành phố Điện Biên Phủ',
    type: 'Thành phố',
    provinceId: '11',
  },
  {
    districtId: '095',
    name: 'Thị Xã Mường Lay',
    type: 'Thị xã',
    provinceId: '11',
  },
  {
    districtId: '096',
    name: 'Huyện Mường Nhé',
    type: 'Huyện',
    provinceId: '11',
  },
  {
    districtId: '097',
    name: 'Huyện Mường Chà',
    type: 'Huyện',
    provinceId: '11',
  },
  {
    districtId: '098',
    name: 'Huyện Tủa Chùa',
    type: 'Huyện',
    provinceId: '11',
  },
  {
    districtId: '099',
    name: 'Huyện Tuần Giáo',
    type: 'Huyện',
    provinceId: '11',
  },
  {
    districtId: '100',
    name: 'Huyện Điện Biên',
    type: 'Huyện',
    provinceId: '11',
  },
  {
    districtId: '101',
    name: 'Huyện Điện Biên Đông',
    type: 'Huyện',
    provinceId: '11',
  },
  {
    districtId: '102',
    name: 'Huyện Mường Ảng',
    type: 'Huyện',
    provinceId: '11',
  },
  {
    districtId: '103',
    name: 'Huyện Nậm Pồ',
    type: 'Huyện',
    provinceId: '11',
  },
  {
    districtId: '105',
    name: 'Thành phố Lai Châu',
    type: 'Thành phố',
    provinceId: '12',
  },
  {
    districtId: '106',
    name: 'Huyện Tam Đường',
    type: 'Huyện',
    provinceId: '12',
  },
  {
    districtId: '107',
    name: 'Huyện Mường Tè',
    type: 'Huyện',
    provinceId: '12',
  },
  {
    districtId: '108',
    name: 'Huyện Sìn Hồ',
    type: 'Huyện',
    provinceId: '12',
  },
  {
    districtId: '109',
    name: 'Huyện Phong Thổ',
    type: 'Huyện',
    provinceId: '12',
  },
  {
    districtId: '110',
    name: 'Huyện Than Uyên',
    type: 'Huyện',
    provinceId: '12',
  },
  {
    districtId: '111',
    name: 'Huyện Tân Uyên',
    type: 'Huyện',
    provinceId: '12',
  },
  {
    districtId: '112',
    name: 'Huyện Nậm Nhùn',
    type: 'Huyện',
    provinceId: '12',
  },
  {
    districtId: '116',
    name: 'Thành phố Sơn La',
    type: 'Thành phố',
    provinceId: '14',
  },
  {
    districtId: '118',
    name: 'Huyện Quỳnh Nhai',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '119',
    name: 'Huyện Thuận Châu',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '120',
    name: 'Huyện Mường La',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '121',
    name: 'Huyện Bắc Yên',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '122',
    name: 'Huyện Phù Yên',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '123',
    name: 'Huyện Mộc Châu',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '124',
    name: 'Huyện Yên Châu',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '125',
    name: 'Huyện Mai Sơn',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '126',
    name: 'Huyện Sông Mã',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '127',
    name: 'Huyện Sốp Cộp',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '128',
    name: 'Huyện Vân Hồ',
    type: 'Huyện',
    provinceId: '14',
  },
  {
    districtId: '132',
    name: 'Thành phố Yên Bái',
    type: 'Thành phố',
    provinceId: '15',
  },
  {
    districtId: '133',
    name: 'Thị xã Nghĩa Lộ',
    type: 'Thị xã',
    provinceId: '15',
  },
  {
    districtId: '135',
    name: 'Huyện Lục Yên',
    type: 'Huyện',
    provinceId: '15',
  },
  {
    districtId: '136',
    name: 'Huyện Văn Yên',
    type: 'Huyện',
    provinceId: '15',
  },
  {
    districtId: '137',
    name: 'Huyện Mù Căng Chải',
    type: 'Huyện',
    provinceId: '15',
  },
  {
    districtId: '138',
    name: 'Huyện Trấn Yên',
    type: 'Huyện',
    provinceId: '15',
  },
  {
    districtId: '139',
    name: 'Huyện Trạm Tấu',
    type: 'Huyện',
    provinceId: '15',
  },
  {
    districtId: '140',
    name: 'Huyện Văn Chấn',
    type: 'Huyện',
    provinceId: '15',
  },
  {
    districtId: '141',
    name: 'Huyện Yên Bình',
    type: 'Huyện',
    provinceId: '15',
  },
  {
    districtId: '148',
    name: 'Thành phố Hòa Bình',
    type: 'Thành phố',
    provinceId: '17',
  },
  {
    districtId: '150',
    name: 'Huyện Đà Bắc',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '151',
    name: 'Huyện Kỳ Sơn',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '152',
    name: 'Huyện Lương Sơn',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '153',
    name: 'Huyện Kim Bôi',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '154',
    name: 'Huyện Cao Phong',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '155',
    name: 'Huyện Tân Lạc',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '156',
    name: 'Huyện Mai Châu',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '157',
    name: 'Huyện Lạc Sơn',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '158',
    name: 'Huyện Yên Thủy',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '159',
    name: 'Huyện Lạc Thủy',
    type: 'Huyện',
    provinceId: '17',
  },
  {
    districtId: '164',
    name: 'Thành phố Thái Nguyên',
    type: 'Thành phố',
    provinceId: '19',
  },
  {
    districtId: '165',
    name: 'Thành phố Sông Công',
    type: 'Thành phố',
    provinceId: '19',
  },
  {
    districtId: '167',
    name: 'Huyện Định Hóa',
    type: 'Huyện',
    provinceId: '19',
  },
  {
    districtId: '168',
    name: 'Huyện Phú Lương',
    type: 'Huyện',
    provinceId: '19',
  },
  {
    districtId: '169',
    name: 'Huyện Đồng Hỷ',
    type: 'Huyện',
    provinceId: '19',
  },
  {
    districtId: '170',
    name: 'Huyện Võ Nhai',
    type: 'Huyện',
    provinceId: '19',
  },
  {
    districtId: '171',
    name: 'Huyện Đại Từ',
    type: 'Huyện',
    provinceId: '19',
  },
  {
    districtId: '172',
    name: 'Thị xã Phổ Yên',
    type: 'Thị xã',
    provinceId: '19',
  },
  {
    districtId: '173',
    name: 'Huyện Phú Bình',
    type: 'Huyện',
    provinceId: '19',
  },
  {
    districtId: '178',
    name: 'Thành phố Lạng Sơn',
    type: 'Thành phố',
    provinceId: '20',
  },
  {
    districtId: '180',
    name: 'Huyện Tràng Định',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '181',
    name: 'Huyện Bình Gia',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '182',
    name: 'Huyện Văn Lãng',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '183',
    name: 'Huyện Cao Lộc',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '184',
    name: 'Huyện Văn Quan',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '185',
    name: 'Huyện Bắc Sơn',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '186',
    name: 'Huyện Hữu Lũng',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '187',
    name: 'Huyện Chi Lăng',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '188',
    name: 'Huyện Lộc Bình',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '189',
    name: 'Huyện Đình Lập',
    type: 'Huyện',
    provinceId: '20',
  },
  {
    districtId: '193',
    name: 'Thành phố Hạ Long',
    type: 'Thành phố',
    provinceId: '22',
  },
  {
    districtId: '194',
    name: 'Thành phố Móng Cái',
    type: 'Thành phố',
    provinceId: '22',
  },
  {
    districtId: '195',
    name: 'Thành phố Cẩm Phả',
    type: 'Thành phố',
    provinceId: '22',
  },
  {
    districtId: '196',
    name: 'Thành phố Uông Bí',
    type: 'Thành phố',
    provinceId: '22',
  },
  {
    districtId: '198',
    name: 'Huyện Bình Liêu',
    type: 'Huyện',
    provinceId: '22',
  },
  {
    districtId: '199',
    name: 'Huyện Tiên Yên',
    type: 'Huyện',
    provinceId: '22',
  },
  {
    districtId: '200',
    name: 'Huyện Đầm Hà',
    type: 'Huyện',
    provinceId: '22',
  },
  {
    districtId: '201',
    name: 'Huyện Hải Hà',
    type: 'Huyện',
    provinceId: '22',
  },
  {
    districtId: '202',
    name: 'Huyện Ba Chẽ',
    type: 'Huyện',
    provinceId: '22',
  },
  {
    districtId: '203',
    name: 'Huyện Vân Đồn',
    type: 'Huyện',
    provinceId: '22',
  },
  {
    districtId: '204',
    name: 'Huyện Hoành Bồ',
    type: 'Huyện',
    provinceId: '22',
  },
  {
    districtId: '205',
    name: 'Thị xã Đông Triều',
    type: 'Thị xã',
    provinceId: '22',
  },
  {
    districtId: '206',
    name: 'Thị xã Quảng Yên',
    type: 'Thị xã',
    provinceId: '22',
  },
  {
    districtId: '207',
    name: 'Huyện Cô Tô',
    type: 'Huyện',
    provinceId: '22',
  },
  {
    districtId: '213',
    name: 'Thành phố Bắc Giang',
    type: 'Thành phố',
    provinceId: '24',
  },
  {
    districtId: '215',
    name: 'Huyện Yên Thế',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '216',
    name: 'Huyện Tân Yên',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '217',
    name: 'Huyện Lạng Giang',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '218',
    name: 'Huyện Lục Nam',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '219',
    name: 'Huyện Lục Ngạn',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '220',
    name: 'Huyện Sơn Động',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '221',
    name: 'Huyện Yên Dũng',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '222',
    name: 'Huyện Việt Yên',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '223',
    name: 'Huyện Hiệp Hòa',
    type: 'Huyện',
    provinceId: '24',
  },
  {
    districtId: '227',
    name: 'Thành phố Việt Trì',
    type: 'Thành phố',
    provinceId: '25',
  },
  {
    districtId: '228',
    name: 'Thị xã Phú Thọ',
    type: 'Thị xã',
    provinceId: '25',
  },
  {
    districtId: '230',
    name: 'Huyện Đoan Hùng',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '231',
    name: 'Huyện Hạ Hoà',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '232',
    name: 'Huyện Thanh Ba',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '233',
    name: 'Huyện Phù Ninh',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '234',
    name: 'Huyện Yên Lập',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '235',
    name: 'Huyện Cẩm Khê',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '236',
    name: 'Huyện Tam Nông',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '237',
    name: 'Huyện Lâm Thao',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '238',
    name: 'Huyện Thanh Sơn',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '239',
    name: 'Huyện Thanh Thuỷ',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '240',
    name: 'Huyện Tân Sơn',
    type: 'Huyện',
    provinceId: '25',
  },
  {
    districtId: '243',
    name: 'Thành phố Vĩnh Yên',
    type: 'Thành phố',
    provinceId: '26',
  },
  {
    districtId: '244',
    name: 'Thị xã Phúc Yên',
    type: 'Thị xã',
    provinceId: '26',
  },
  {
    districtId: '246',
    name: 'Huyện Lập Thạch',
    type: 'Huyện',
    provinceId: '26',
  },
  {
    districtId: '247',
    name: 'Huyện Tam Dương',
    type: 'Huyện',
    provinceId: '26',
  },
  {
    districtId: '248',
    name: 'Huyện Tam Đảo',
    type: 'Huyện',
    provinceId: '26',
  },
  {
    districtId: '249',
    name: 'Huyện Bình Xuyên',
    type: 'Huyện',
    provinceId: '26',
  },
  {
    districtId: '250',
    name: 'Huyện Mê Linh',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '251',
    name: 'Huyện Yên Lạc',
    type: 'Huyện',
    provinceId: '26',
  },
  {
    districtId: '252',
    name: 'Huyện Vĩnh Tường',
    type: 'Huyện',
    provinceId: '26',
  },
  {
    districtId: '253',
    name: 'Huyện Sông Lô',
    type: 'Huyện',
    provinceId: '26',
  },
  {
    districtId: '256',
    name: 'Thành phố Bắc Ninh',
    type: 'Thành phố',
    provinceId: '27',
  },
  {
    districtId: '258',
    name: 'Huyện Yên Phong',
    type: 'Huyện',
    provinceId: '27',
  },
  {
    districtId: '259',
    name: 'Huyện Quế Võ',
    type: 'Huyện',
    provinceId: '27',
  },
  {
    districtId: '260',
    name: 'Huyện Tiên Du',
    type: 'Huyện',
    provinceId: '27',
  },
  {
    districtId: '261',
    name: 'Thị xã Từ Sơn',
    type: 'Thị xã',
    provinceId: '27',
  },
  {
    districtId: '262',
    name: 'Huyện Thuận Thành',
    type: 'Huyện',
    provinceId: '27',
  },
  {
    districtId: '263',
    name: 'Huyện Gia Bình',
    type: 'Huyện',
    provinceId: '27',
  },
  {
    districtId: '264',
    name: 'Huyện Lương Tài',
    type: 'Huyện',
    provinceId: '27',
  },
  {
    districtId: '268',
    name: 'Quận Hà Đông',
    type: 'Quận',
    provinceId: '01',
  },
  {
    districtId: '269',
    name: 'Thị xã Sơn Tây',
    type: 'Thị xã',
    provinceId: '01',
  },
  {
    districtId: '271',
    name: 'Huyện Ba Vì',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '272',
    name: 'Huyện Phúc Thọ',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '273',
    name: 'Huyện Đan Phượng',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '274',
    name: 'Huyện Hoài Đức',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '275',
    name: 'Huyện Quốc Oai',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '276',
    name: 'Huyện Thạch Thất',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '277',
    name: 'Huyện Chương Mỹ',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '278',
    name: 'Huyện Thanh Oai',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '279',
    name: 'Huyện Thường Tín',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '280',
    name: 'Huyện Phú Xuyên',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '281',
    name: 'Huyện Ứng Hòa',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '282',
    name: 'Huyện Mỹ Đức',
    type: 'Huyện',
    provinceId: '01',
  },
  {
    districtId: '288',
    name: 'Thành phố Hải Dương',
    type: 'Thành phố',
    provinceId: '30',
  },
  {
    districtId: '290',
    name: 'Thị xã Chí Linh',
    type: 'Thị xã',
    provinceId: '30',
  },
  {
    districtId: '291',
    name: 'Huyện Nam Sách',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '292',
    name: 'Huyện Kinh Môn',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '293',
    name: 'Huyện Kim Thành',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '294',
    name: 'Huyện Thanh Hà',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '295',
    name: 'Huyện Cẩm Giàng',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '296',
    name: 'Huyện Bình Giang',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '297',
    name: 'Huyện Gia Lộc',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '298',
    name: 'Huyện Tứ Kỳ',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '299',
    name: 'Huyện Ninh Giang',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '300',
    name: 'Huyện Thanh Miện',
    type: 'Huyện',
    provinceId: '30',
  },
  {
    districtId: '303',
    name: 'Quận Hồng Bàng',
    type: 'Quận',
    provinceId: '31',
  },
  {
    districtId: '304',
    name: 'Quận Ngô Quyền',
    type: 'Quận',
    provinceId: '31',
  },
  {
    districtId: '305',
    name: 'Quận Lê Chân',
    type: 'Quận',
    provinceId: '31',
  },
  {
    districtId: '306',
    name: 'Quận Hải An',
    type: 'Quận',
    provinceId: '31',
  },
  {
    districtId: '307',
    name: 'Quận Kiến An',
    type: 'Quận',
    provinceId: '31',
  },
  {
    districtId: '308',
    name: 'Quận Đồ Sơn',
    type: 'Quận',
    provinceId: '31',
  },
  {
    districtId: '309',
    name: 'Quận Dương Kinh',
    type: 'Quận',
    provinceId: '31',
  },
  {
    districtId: '311',
    name: 'Huyện Thuỷ Nguyên',
    type: 'Huyện',
    provinceId: '31',
  },
  {
    districtId: '312',
    name: 'Huyện An Dương',
    type: 'Huyện',
    provinceId: '31',
  },
  {
    districtId: '313',
    name: 'Huyện An Lão',
    type: 'Huyện',
    provinceId: '31',
  },
  {
    districtId: '314',
    name: 'Huyện Kiến Thuỵ',
    type: 'Huyện',
    provinceId: '31',
  },
  {
    districtId: '315',
    name: 'Huyện Tiên Lãng',
    type: 'Huyện',
    provinceId: '31',
  },
  {
    districtId: '316',
    name: 'Huyện Vĩnh Bảo',
    type: 'Huyện',
    provinceId: '31',
  },
  {
    districtId: '317',
    name: 'Huyện Cát Hải',
    type: 'Huyện',
    provinceId: '31',
  },
  {
    districtId: '318',
    name: 'Huyện Bạch Long Vĩ',
    type: 'Huyện',
    provinceId: '31',
  },
  {
    districtId: '323',
    name: 'Thành phố Hưng Yên',
    type: 'Thành phố',
    provinceId: '33',
  },
  {
    districtId: '325',
    name: 'Huyện Văn Lâm',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '326',
    name: 'Huyện Văn Giang',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '327',
    name: 'Huyện Yên Mỹ',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '328',
    name: 'Huyện Mỹ Hào',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '329',
    name: 'Huyện Ân Thi',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '330',
    name: 'Huyện Khoái Châu',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '331',
    name: 'Huyện Kim Động',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '332',
    name: 'Huyện Tiên Lữ',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '333',
    name: 'Huyện Phù Cừ',
    type: 'Huyện',
    provinceId: '33',
  },
  {
    districtId: '336',
    name: 'Thành phố Thái Bình',
    type: 'Thành phố',
    provinceId: '34',
  },
  {
    districtId: '338',
    name: 'Huyện Quỳnh Phụ',
    type: 'Huyện',
    provinceId: '34',
  },
  {
    districtId: '339',
    name: 'Huyện Hưng Hà',
    type: 'Huyện',
    provinceId: '34',
  },
  {
    districtId: '340',
    name: 'Huyện Đông Hưng',
    type: 'Huyện',
    provinceId: '34',
  },
  {
    districtId: '341',
    name: 'Huyện Thái Thụy',
    type: 'Huyện',
    provinceId: '34',
  },
  {
    districtId: '342',
    name: 'Huyện Tiền Hải',
    type: 'Huyện',
    provinceId: '34',
  },
  {
    districtId: '343',
    name: 'Huyện Kiến Xương',
    type: 'Huyện',
    provinceId: '34',
  },
  {
    districtId: '344',
    name: 'Huyện Vũ Thư',
    type: 'Huyện',
    provinceId: '34',
  },
  {
    districtId: '347',
    name: 'Thành phố Phủ Lý',
    type: 'Thành phố',
    provinceId: '35',
  },
  {
    districtId: '349',
    name: 'Huyện Duy Tiên',
    type: 'Huyện',
    provinceId: '35',
  },
  {
    districtId: '350',
    name: 'Huyện Kim Bảng',
    type: 'Huyện',
    provinceId: '35',
  },
  {
    districtId: '351',
    name: 'Huyện Thanh Liêm',
    type: 'Huyện',
    provinceId: '35',
  },
  {
    districtId: '352',
    name: 'Huyện Bình Lục',
    type: 'Huyện',
    provinceId: '35',
  },
  {
    districtId: '353',
    name: 'Huyện Lý Nhân',
    type: 'Huyện',
    provinceId: '35',
  },
  {
    districtId: '356',
    name: 'Thành phố Nam Định',
    type: 'Thành phố',
    provinceId: '36',
  },
  {
    districtId: '358',
    name: 'Huyện Mỹ Lộc',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '359',
    name: 'Huyện Vụ Bản',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '360',
    name: 'Huyện Ý Yên',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '361',
    name: 'Huyện Nghĩa Hưng',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '362',
    name: 'Huyện Nam Trực',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '363',
    name: 'Huyện Trực Ninh',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '364',
    name: 'Huyện Xuân Trường',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '365',
    name: 'Huyện Giao Thủy',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '366',
    name: 'Huyện Hải Hậu',
    type: 'Huyện',
    provinceId: '36',
  },
  {
    districtId: '369',
    name: 'Thành phố Ninh Bình',
    type: 'Thành phố',
    provinceId: '37',
  },
  {
    districtId: '370',
    name: 'Thành phố Tam Điệp',
    type: 'Thành phố',
    provinceId: '37',
  },
  {
    districtId: '372',
    name: 'Huyện Nho Quan',
    type: 'Huyện',
    provinceId: '37',
  },
  {
    districtId: '373',
    name: 'Huyện Gia Viễn',
    type: 'Huyện',
    provinceId: '37',
  },
  {
    districtId: '374',
    name: 'Huyện Hoa Lư',
    type: 'Huyện',
    provinceId: '37',
  },
  {
    districtId: '375',
    name: 'Huyện Yên Khánh',
    type: 'Huyện',
    provinceId: '37',
  },
  {
    districtId: '376',
    name: 'Huyện Kim Sơn',
    type: 'Huyện',
    provinceId: '37',
  },
  {
    districtId: '377',
    name: 'Huyện Yên Mô',
    type: 'Huyện',
    provinceId: '37',
  },
  {
    districtId: '380',
    name: 'Thành phố Thanh Hóa',
    type: 'Thành phố',
    provinceId: '38',
  },
  {
    districtId: '381',
    name: 'Thị xã Bỉm Sơn',
    type: 'Thị xã',
    provinceId: '38',
  },
  {
    districtId: '382',
    name: 'Thị xã Sầm Sơn',
    type: 'Thị xã',
    provinceId: '38',
  },
  {
    districtId: '384',
    name: 'Huyện Mường Lát',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '385',
    name: 'Huyện Quan Hóa',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '386',
    name: 'Huyện Bá Thước',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '387',
    name: 'Huyện Quan Sơn',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '388',
    name: 'Huyện Lang Chánh',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '389',
    name: 'Huyện Ngọc Lặc',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '390',
    name: 'Huyện Cẩm Thủy',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '391',
    name: 'Huyện Thạch Thành',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '392',
    name: 'Huyện Hà Trung',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '393',
    name: 'Huyện Vĩnh Lộc',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '394',
    name: 'Huyện Yên Định',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '395',
    name: 'Huyện Thọ Xuân',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '396',
    name: 'Huyện Thường Xuân',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '397',
    name: 'Huyện Triệu Sơn',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '398',
    name: 'Huyện Thiệu Hóa',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '399',
    name: 'Huyện Hoằng Hóa',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '400',
    name: 'Huyện Hậu Lộc',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '401',
    name: 'Huyện Nga Sơn',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '402',
    name: 'Huyện Như Xuân',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '403',
    name: 'Huyện Như Thanh',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '404',
    name: 'Huyện Nông Cống',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '405',
    name: 'Huyện Đông Sơn',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '406',
    name: 'Huyện Quảng Xương',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '407',
    name: 'Huyện Tĩnh Gia',
    type: 'Huyện',
    provinceId: '38',
  },
  {
    districtId: '412',
    name: 'Thành phố Vinh',
    type: 'Thành phố',
    provinceId: '40',
  },
  {
    districtId: '413',
    name: 'Thị xã Cửa Lò',
    type: 'Thị xã',
    provinceId: '40',
  },
  {
    districtId: '414',
    name: 'Thị xã Thái Hoà',
    type: 'Thị xã',
    provinceId: '40',
  },
  {
    districtId: '415',
    name: 'Huyện Quế Phong',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '416',
    name: 'Huyện Quỳ Châu',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '417',
    name: 'Huyện Kỳ Sơn',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '418',
    name: 'Huyện Tương Dương',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '419',
    name: 'Huyện Nghĩa Đàn',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '420',
    name: 'Huyện Quỳ Hợp',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '421',
    name: 'Huyện Quỳnh Lưu',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '422',
    name: 'Huyện Con Cuông',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '423',
    name: 'Huyện Tân Kỳ',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '424',
    name: 'Huyện Anh Sơn',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '425',
    name: 'Huyện Diễn Châu',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '426',
    name: 'Huyện Yên Thành',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '427',
    name: 'Huyện Đô Lương',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '428',
    name: 'Huyện Thanh Chương',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '429',
    name: 'Huyện Nghi Lộc',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '430',
    name: 'Huyện Nam Đàn',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '431',
    name: 'Huyện Hưng Nguyên',
    type: 'Huyện',
    provinceId: '40',
  },
  {
    districtId: '432',
    name: 'Thị xã Hoàng Mai',
    type: 'Thị xã',
    provinceId: '40',
  },
  {
    districtId: '436',
    name: 'Thành phố Hà Tĩnh',
    type: 'Thành phố',
    provinceId: '42',
  },
  {
    districtId: '437',
    name: 'Thị xã Hồng Lĩnh',
    type: 'Thị xã',
    provinceId: '42',
  },
  {
    districtId: '439',
    name: 'Huyện Hương Sơn',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '440',
    name: 'Huyện Đức Thọ',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '441',
    name: 'Huyện Vũ Quang',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '442',
    name: 'Huyện Nghi Xuân',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '443',
    name: 'Huyện Can Lộc',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '444',
    name: 'Huyện Hương Khê',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '445',
    name: 'Huyện Thạch Hà',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '446',
    name: 'Huyện Cẩm Xuyên',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '447',
    name: 'Huyện Kỳ Anh',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '448',
    name: 'Huyện Lộc Hà',
    type: 'Huyện',
    provinceId: '42',
  },
  {
    districtId: '449',
    name: 'Thị xã Kỳ Anh',
    type: 'Thị xã',
    provinceId: '42',
  },
  {
    districtId: '450',
    name: 'Thành Phố Đồng Hới',
    type: 'Thành phố',
    provinceId: '44',
  },
  {
    districtId: '452',
    name: 'Huyện Minh Hóa',
    type: 'Huyện',
    provinceId: '44',
  },
  {
    districtId: '453',
    name: 'Huyện Tuyên Hóa',
    type: 'Huyện',
    provinceId: '44',
  },
  {
    districtId: '454',
    name: 'Huyện Quảng Trạch',
    type: 'Thị xã',
    provinceId: '44',
  },
  {
    districtId: '455',
    name: 'Huyện Bố Trạch',
    type: 'Huyện',
    provinceId: '44',
  },
  {
    districtId: '456',
    name: 'Huyện Quảng Ninh',
    type: 'Huyện',
    provinceId: '44',
  },
  {
    districtId: '457',
    name: 'Huyện Lệ Thủy',
    type: 'Huyện',
    provinceId: '44',
  },
  {
    districtId: '458',
    name: 'Thị xã Ba Đồn',
    type: 'Huyện',
    provinceId: '44',
  },
  {
    districtId: '461',
    name: 'Thành phố Đông Hà',
    type: 'Thành phố',
    provinceId: '45',
  },
  {
    districtId: '462',
    name: 'Thị xã Quảng Trị',
    type: 'Thị xã',
    provinceId: '45',
  },
  {
    districtId: '464',
    name: 'Huyện Vĩnh Linh',
    type: 'Huyện',
    provinceId: '45',
  },
  {
    districtId: '465',
    name: 'Huyện Hướng Hóa',
    type: 'Huyện',
    provinceId: '45',
  },
  {
    districtId: '466',
    name: 'Huyện Gio Linh',
    type: 'Huyện',
    provinceId: '45',
  },
  {
    districtId: '467',
    name: 'Huyện Đa Krông',
    type: 'Huyện',
    provinceId: '45',
  },
  {
    districtId: '468',
    name: 'Huyện Cam Lộ',
    type: 'Huyện',
    provinceId: '45',
  },
  {
    districtId: '469',
    name: 'Huyện Triệu Phong',
    type: 'Huyện',
    provinceId: '45',
  },
  {
    districtId: '470',
    name: 'Huyện Hải Lăng',
    type: 'Huyện',
    provinceId: '45',
  },
  {
    districtId: '471',
    name: 'Huyện Cồn Cỏ',
    type: 'Huyện',
    provinceId: '45',
  },
  {
    districtId: '474',
    name: 'Thành phố Huế',
    type: 'Thành phố',
    provinceId: '46',
  },
  {
    districtId: '476',
    name: 'Huyện Phong Điền',
    type: 'Huyện',
    provinceId: '46',
  },
  {
    districtId: '477',
    name: 'Huyện Quảng Điền',
    type: 'Huyện',
    provinceId: '46',
  },
  {
    districtId: '478',
    name: 'Huyện Phú Vang',
    type: 'Huyện',
    provinceId: '46',
  },
  {
    districtId: '479',
    name: 'Thị xã Hương Thủy',
    type: 'Thị xã',
    provinceId: '46',
  },
  {
    districtId: '480',
    name: 'Thị xã Hương Trà',
    type: 'Thị xã',
    provinceId: '46',
  },
  {
    districtId: '481',
    name: 'Huyện A Lưới',
    type: 'Huyện',
    provinceId: '46',
  },
  {
    districtId: '482',
    name: 'Huyện Phú Lộc',
    type: 'Huyện',
    provinceId: '46',
  },
  {
    districtId: '483',
    name: 'Huyện Nam Đông',
    type: 'Huyện',
    provinceId: '46',
  },
  {
    districtId: '490',
    name: 'Quận Liên Chiểu',
    type: 'Quận',
    provinceId: '48',
  },
  {
    districtId: '491',
    name: 'Quận Thanh Khê',
    type: 'Quận',
    provinceId: '48',
  },
  {
    districtId: '492',
    name: 'Quận Hải Châu',
    type: 'Quận',
    provinceId: '48',
  },
  {
    districtId: '493',
    name: 'Quận Sơn Trà',
    type: 'Quận',
    provinceId: '48',
  },
  {
    districtId: '494',
    name: 'Quận Ngũ Hành Sơn',
    type: 'Quận',
    provinceId: '48',
  },
  {
    districtId: '495',
    name: 'Quận Cẩm Lệ',
    type: 'Quận',
    provinceId: '48',
  },
  {
    districtId: '497',
    name: 'Huyện Hòa Vang',
    type: 'Huyện',
    provinceId: '48',
  },
  {
    districtId: '498',
    name: 'Huyện Hoàng Sa',
    type: 'Huyện',
    provinceId: '48',
  },
  {
    districtId: '502',
    name: 'Thành phố Tam Kỳ',
    type: 'Thành phố',
    provinceId: '49',
  },
  {
    districtId: '503',
    name: 'Thành phố Hội An',
    type: 'Thành phố',
    provinceId: '49',
  },
  {
    districtId: '504',
    name: 'Huyện Tây Giang',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '505',
    name: 'Huyện Đông Giang',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '506',
    name: 'Huyện Đại Lộc',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '507',
    name: 'Thị xã Điện Bàn',
    type: 'Thị xã',
    provinceId: '49',
  },
  {
    districtId: '508',
    name: 'Huyện Duy Xuyên',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '509',
    name: 'Huyện Quế Sơn',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '510',
    name: 'Huyện Nam Giang',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '511',
    name: 'Huyện Phước Sơn',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '512',
    name: 'Huyện Hiệp Đức',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '513',
    name: 'Huyện Thăng Bình',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '514',
    name: 'Huyện Tiên Phước',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '515',
    name: 'Huyện Bắc Trà My',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '516',
    name: 'Huyện Nam Trà My',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '517',
    name: 'Huyện Núi Thành',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '518',
    name: 'Huyện Phú Ninh',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '519',
    name: 'Huyện Nông Sơn',
    type: 'Huyện',
    provinceId: '49',
  },
  {
    districtId: '522',
    name: 'Thành phố Quảng Ngãi',
    type: 'Thành phố',
    provinceId: '51',
  },
  {
    districtId: '524',
    name: 'Huyện Bình Sơn',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '525',
    name: 'Huyện Trà Bồng',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '526',
    name: 'Huyện Tây Trà',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '527',
    name: 'Huyện Sơn Tịnh',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '528',
    name: 'Huyện Tư Nghĩa',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '529',
    name: 'Huyện Sơn Hà',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '530',
    name: 'Huyện Sơn Tây',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '531',
    name: 'Huyện Minh Long',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '532',
    name: 'Huyện Nghĩa Hành',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '533',
    name: 'Huyện Mộ Đức',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '534',
    name: 'Huyện Đức Phổ',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '535',
    name: 'Huyện Ba Tơ',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '536',
    name: 'Huyện Lý Sơn',
    type: 'Huyện',
    provinceId: '51',
  },
  {
    districtId: '540',
    name: 'Thành phố Qui Nhơn',
    type: 'Thành phố',
    provinceId: '52',
  },
  {
    districtId: '542',
    name: 'Huyện An Lão',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '543',
    name: 'Huyện Hoài Nhơn',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '544',
    name: 'Huyện Hoài Ân',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '545',
    name: 'Huyện Phù Mỹ',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '546',
    name: 'Huyện Vĩnh Thạnh',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '547',
    name: 'Huyện Tây Sơn',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '548',
    name: 'Huyện Phù Cát',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '549',
    name: 'Thị xã An Nhơn',
    type: 'Thị xã',
    provinceId: '52',
  },
  {
    districtId: '550',
    name: 'Huyện Tuy Phước',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '551',
    name: 'Huyện Vân Canh',
    type: 'Huyện',
    provinceId: '52',
  },
  {
    districtId: '555',
    name: 'Thành phố Tuy Hoà',
    type: 'Thành phố',
    provinceId: '54',
  },
  {
    districtId: '557',
    name: 'Thị xã Sông Cầu',
    type: 'Thị xã',
    provinceId: '54',
  },
  {
    districtId: '558',
    name: 'Huyện Đồng Xuân',
    type: 'Huyện',
    provinceId: '54',
  },
  {
    districtId: '559',
    name: 'Huyện Tuy An',
    type: 'Huyện',
    provinceId: '54',
  },
  {
    districtId: '560',
    name: 'Huyện Sơn Hòa',
    type: 'Huyện',
    provinceId: '54',
  },
  {
    districtId: '561',
    name: 'Huyện Sông Hinh',
    type: 'Huyện',
    provinceId: '54',
  },
  {
    districtId: '562',
    name: 'Huyện Tây Hoà',
    type: 'Huyện',
    provinceId: '54',
  },
  {
    districtId: '563',
    name: 'Huyện Phú Hoà',
    type: 'Huyện',
    provinceId: '54',
  },
  {
    districtId: '564',
    name: 'Huyện Đông Hòa',
    type: 'Huyện',
    provinceId: '54',
  },
  {
    districtId: '568',
    name: 'Thành phố Nha Trang',
    type: 'Thành phố',
    provinceId: '56',
  },
  {
    districtId: '569',
    name: 'Thành phố Cam Ranh',
    type: 'Thành phố',
    provinceId: '56',
  },
  {
    districtId: '570',
    name: 'Huyện Cam Lâm',
    type: 'Huyện',
    provinceId: '56',
  },
  {
    districtId: '571',
    name: 'Huyện Vạn Ninh',
    type: 'Huyện',
    provinceId: '56',
  },
  {
    districtId: '572',
    name: 'Thị xã Ninh Hòa',
    type: 'Thị xã',
    provinceId: '56',
  },
  {
    districtId: '573',
    name: 'Huyện Khánh Vĩnh',
    type: 'Huyện',
    provinceId: '56',
  },
  {
    districtId: '574',
    name: 'Huyện Diên Khánh',
    type: 'Huyện',
    provinceId: '56',
  },
  {
    districtId: '575',
    name: 'Huyện Khánh Sơn',
    type: 'Huyện',
    provinceId: '56',
  },
  {
    districtId: '576',
    name: 'Huyện Trường Sa',
    type: 'Huyện',
    provinceId: '56',
  },
  {
    districtId: '582',
    name: 'Thành phố Phan Rang-Tháp Chàm',
    type: 'Thành phố',
    provinceId: '58',
  },
  {
    districtId: '584',
    name: 'Huyện Bác Ái',
    type: 'Huyện',
    provinceId: '58',
  },
  {
    districtId: '585',
    name: 'Huyện Ninh Sơn',
    type: 'Huyện',
    provinceId: '58',
  },
  {
    districtId: '586',
    name: 'Huyện Ninh Hải',
    type: 'Huyện',
    provinceId: '58',
  },
  {
    districtId: '587',
    name: 'Huyện Ninh Phước',
    type: 'Huyện',
    provinceId: '58',
  },
  {
    districtId: '588',
    name: 'Huyện Thuận Bắc',
    type: 'Huyện',
    provinceId: '58',
  },
  {
    districtId: '589',
    name: 'Huyện Thuận Nam',
    type: 'Huyện',
    provinceId: '58',
  },
  {
    districtId: '593',
    name: 'Thành phố Phan Thiết',
    type: 'Thành phố',
    provinceId: '60',
  },
  {
    districtId: '594',
    name: 'Thị xã La Gi',
    type: 'Thị xã',
    provinceId: '60',
  },
  {
    districtId: '595',
    name: 'Huyện Tuy Phong',
    type: 'Huyện',
    provinceId: '60',
  },
  {
    districtId: '596',
    name: 'Huyện Bắc Bình',
    type: 'Huyện',
    provinceId: '60',
  },
  {
    districtId: '597',
    name: 'Huyện Hàm Thuận Bắc',
    type: 'Huyện',
    provinceId: '60',
  },
  {
    districtId: '598',
    name: 'Huyện Hàm Thuận Nam',
    type: 'Huyện',
    provinceId: '60',
  },
  {
    districtId: '599',
    name: 'Huyện Tánh Linh',
    type: 'Huyện',
    provinceId: '60',
  },
  {
    districtId: '600',
    name: 'Huyện Đức Linh',
    type: 'Huyện',
    provinceId: '60',
  },
  {
    districtId: '601',
    name: 'Huyện Hàm Tân',
    type: 'Huyện',
    provinceId: '60',
  },
  {
    districtId: '602',
    name: 'Huyện Phú Quí',
    type: 'Huyện',
    provinceId: '60',
  },
  {
    districtId: '608',
    name: 'Thành phố Kon Tum',
    type: 'Thành phố',
    provinceId: '62',
  },
  {
    districtId: '610',
    name: 'Huyện Đắk Glei',
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '611',
    name: 'Huyện Ngọc Hồi',
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '612',
    name: 'Huyện Đắk Tô',
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '613',
    name: 'Huyện Kon Plông',
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '614',
    name: 'Huyện Kon Rẫy',
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '615',
    name: 'Huyện Đắk Hà',
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '616',
    name: 'Huyện Sa Thầy',
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '617',
    name: 'Huyện Tu Mơ Rông',
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '618',
    name: "Huyện Ia H' Drai",
    type: 'Huyện',
    provinceId: '62',
  },
  {
    districtId: '622',
    name: 'Thành phố Pleiku',
    type: 'Thành phố',
    provinceId: '64',
  },
  {
    districtId: '623',
    name: 'Thị xã An Khê',
    type: 'Thị xã',
    provinceId: '64',
  },
  {
    districtId: '624',
    name: 'Thị xã Ayun Pa',
    type: 'Thị xã',
    provinceId: '64',
  },
  {
    districtId: '625',
    name: 'Huyện KBang',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '626',
    name: 'Huyện Đăk Đoa',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '627',
    name: 'Huyện Chư Păh',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '628',
    name: 'Huyện Ia Grai',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '629',
    name: 'Huyện Mang Yang',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '630',
    name: 'Huyện Kông Chro',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '631',
    name: 'Huyện Đức Cơ',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '632',
    name: 'Huyện Chư Prông',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '633',
    name: 'Huyện Chư Sê',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '634',
    name: 'Huyện Đăk Pơ',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '635',
    name: 'Huyện Ia Pa',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '637',
    name: 'Huyện Krông Pa',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '638',
    name: 'Huyện Phú Thiện',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '639',
    name: 'Huyện Chư Pưh',
    type: 'Huyện',
    provinceId: '64',
  },
  {
    districtId: '643',
    name: 'Thành phố Buôn Ma Thuột',
    type: 'Thành phố',
    provinceId: '66',
  },
  {
    districtId: '644',
    name: 'Thị Xã Buôn Hồ',
    type: 'Thị xã',
    provinceId: '66',
  },
  {
    districtId: '645',
    name: "Huyện Ea H'leo",
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '646',
    name: 'Huyện Ea Súp',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '647',
    name: 'Huyện Buôn Đôn',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '648',
    name: "Huyện Cư M'gar",
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '649',
    name: 'Huyện Krông Búk',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '650',
    name: 'Huyện Krông Năng',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '651',
    name: 'Huyện Ea Kar',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '652',
    name: "Huyện M'Đrắk",
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '653',
    name: 'Huyện Krông Bông',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '654',
    name: 'Huyện Krông Pắc',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '655',
    name: 'Huyện Krông A Na',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '656',
    name: 'Huyện Lắk',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '657',
    name: 'Huyện Cư Kuin',
    type: 'Huyện',
    provinceId: '66',
  },
  {
    districtId: '660',
    name: 'Thị xã Gia Nghĩa',
    type: 'Thị xã',
    provinceId: '67',
  },
  {
    districtId: '661',
    name: 'Huyện Đăk Glong',
    type: 'Huyện',
    provinceId: '67',
  },
  {
    districtId: '662',
    name: 'Huyện Cư Jút',
    type: 'Huyện',
    provinceId: '67',
  },
  {
    districtId: '663',
    name: 'Huyện Đắk Mil',
    type: 'Huyện',
    provinceId: '67',
  },
  {
    districtId: '664',
    name: 'Huyện Krông Nô',
    type: 'Huyện',
    provinceId: '67',
  },
  {
    districtId: '665',
    name: 'Huyện Đắk Song',
    type: 'Huyện',
    provinceId: '67',
  },
  {
    districtId: '666',
    name: "Huyện Đắk R'Lấp",
    type: 'Huyện',
    provinceId: '67',
  },
  {
    districtId: '667',
    name: 'Huyện Tuy Đức',
    type: 'Huyện',
    provinceId: '67',
  },
  {
    districtId: '672',
    name: 'Thành phố Đà Lạt',
    type: 'Thành phố',
    provinceId: '68',
  },
  {
    districtId: '673',
    name: 'Thành phố Bảo Lộc',
    type: 'Thành phố',
    provinceId: '68',
  },
  {
    districtId: '674',
    name: 'Huyện Đam Rông',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '675',
    name: 'Huyện Lạc Dương',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '676',
    name: 'Huyện Lâm Hà',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '677',
    name: 'Huyện Đơn Dương',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '678',
    name: 'Huyện Đức Trọng',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '679',
    name: 'Huyện Di Linh',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '680',
    name: 'Huyện Bảo Lâm',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '681',
    name: 'Huyện Đạ Huoai',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '682',
    name: 'Huyện Đạ Tẻh',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '683',
    name: 'Huyện Cát Tiên',
    type: 'Huyện',
    provinceId: '68',
  },
  {
    districtId: '688',
    name: 'Thị xã Phước Long',
    type: 'Thị xã',
    provinceId: '70',
  },
  {
    districtId: '689',
    name: 'Thị xã Đồng Xoài',
    type: 'Thị xã',
    provinceId: '70',
  },
  {
    districtId: '690',
    name: 'Thị xã Bình Long',
    type: 'Thị xã',
    provinceId: '70',
  },
  {
    districtId: '691',
    name: 'Huyện Bù Gia Mập',
    type: 'Huyện',
    provinceId: '70',
  },
  {
    districtId: '692',
    name: 'Huyện Lộc Ninh',
    type: 'Huyện',
    provinceId: '70',
  },
  {
    districtId: '693',
    name: 'Huyện Bù Đốp',
    type: 'Huyện',
    provinceId: '70',
  },
  {
    districtId: '694',
    name: 'Huyện Hớn Quản',
    type: 'Huyện',
    provinceId: '70',
  },
  {
    districtId: '695',
    name: 'Huyện Đồng Phú',
    type: 'Huyện',
    provinceId: '70',
  },
  {
    districtId: '696',
    name: 'Huyện Bù Đăng',
    type: 'Huyện',
    provinceId: '70',
  },
  {
    districtId: '697',
    name: 'Huyện Chơn Thành',
    type: 'Huyện',
    provinceId: '70',
  },
  {
    districtId: '698',
    name: 'Huyện Phú Riềng',
    type: 'Huyện',
    provinceId: '70',
  },
  {
    districtId: '703',
    name: 'Thành phố Tây Ninh',
    type: 'Thành phố',
    provinceId: '72',
  },
  {
    districtId: '705',
    name: 'Huyện Tân Biên',
    type: 'Huyện',
    provinceId: '72',
  },
  {
    districtId: '706',
    name: 'Huyện Tân Châu',
    type: 'Huyện',
    provinceId: '72',
  },
  {
    districtId: '707',
    name: 'Huyện Dương Minh Châu',
    type: 'Huyện',
    provinceId: '72',
  },
  {
    districtId: '708',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '72',
  },
  {
    districtId: '709',
    name: 'Huyện Hòa Thành',
    type: 'Huyện',
    provinceId: '72',
  },
  {
    districtId: '710',
    name: 'Huyện Gò Dầu',
    type: 'Huyện',
    provinceId: '72',
  },
  {
    districtId: '711',
    name: 'Huyện Bến Cầu',
    type: 'Huyện',
    provinceId: '72',
  },
  {
    districtId: '712',
    name: 'Huyện Trảng Bàng',
    type: 'Huyện',
    provinceId: '72',
  },
  {
    districtId: '718',
    name: 'Thành phố Thủ Dầu Một',
    type: 'Thành phố',
    provinceId: '74',
  },
  {
    districtId: '719',
    name: 'Huyện Bàu Bàng',
    type: 'Huyện',
    provinceId: '74',
  },
  {
    districtId: '720',
    name: 'Huyện Dầu Tiếng',
    type: 'Huyện',
    provinceId: '74',
  },
  {
    districtId: '721',
    name: 'Thị xã Bến Cát',
    type: 'Thị xã',
    provinceId: '74',
  },
  {
    districtId: '722',
    name: 'Huyện Phú Giáo',
    type: 'Huyện',
    provinceId: '74',
  },
  {
    districtId: '723',
    name: 'Thị xã Tân Uyên',
    type: 'Thị xã',
    provinceId: '74',
  },
  {
    districtId: '724',
    name: 'Thị xã Dĩ An',
    type: 'Thị xã',
    provinceId: '74',
  },
  {
    districtId: '725',
    name: 'Thị xã Thuận An',
    type: 'Thị xã',
    provinceId: '74',
  },
  {
    districtId: '726',
    name: 'Huyện Bắc Tân Uyên',
    type: 'Huyện',
    provinceId: '74',
  },
  {
    districtId: '731',
    name: 'Thành phố Biên Hòa',
    type: 'Thành phố',
    provinceId: '75',
  },
  {
    districtId: '732',
    name: 'Thị xã Long Khánh',
    type: 'Thị xã',
    provinceId: '75',
  },
  {
    districtId: '734',
    name: 'Huyện Tân Phú',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '735',
    name: 'Huyện Vĩnh Cửu',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '736',
    name: 'Huyện Định Quán',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '737',
    name: 'Huyện Trảng Bom',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '738',
    name: 'Huyện Thống Nhất',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '739',
    name: 'Huyện Cẩm Mỹ',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '740',
    name: 'Huyện Long Thành',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '741',
    name: 'Huyện Xuân Lộc',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '742',
    name: 'Huyện Nhơn Trạch',
    type: 'Huyện',
    provinceId: '75',
  },
  {
    districtId: '747',
    name: 'Thành phố Vũng Tàu',
    type: 'Thành phố',
    provinceId: '77',
  },
  {
    districtId: '748',
    name: 'Thành phố Bà Rịa',
    type: 'Thành phố',
    provinceId: '77',
  },
  {
    districtId: '750',
    name: 'Huyện Châu Đức',
    type: 'Huyện',
    provinceId: '77',
  },
  {
    districtId: '751',
    name: 'Huyện Xuyên Mộc',
    type: 'Huyện',
    provinceId: '77',
  },
  {
    districtId: '752',
    name: 'Huyện Long Điền',
    type: 'Huyện',
    provinceId: '77',
  },
  {
    districtId: '753',
    name: 'Huyện Đất Đỏ',
    type: 'Huyện',
    provinceId: '77',
  },
  {
    districtId: '754',
    name: 'Huyện Tân Thành',
    type: 'Huyện',
    provinceId: '77',
  },
  {
    districtId: '755',
    name: 'Huyện Côn Đảo',
    type: 'Huyện',
    provinceId: '77',
  },
  {
    districtId: '760',
    name: 'Quận 1',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '761',
    name: 'Quận 12',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '762',
    name: 'Quận Thủ Đức',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '763',
    name: 'Quận 9',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '764',
    name: 'Quận Gò Vấp',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '765',
    name: 'Quận Bình Thạnh',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '766',
    name: 'Quận Tân Bình',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '767',
    name: 'Quận Tân Phú',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '768',
    name: 'Quận Phú Nhuận',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '769',
    name: 'Quận 2',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '770',
    name: 'Quận 3',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '771',
    name: 'Quận 10',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '772',
    name: 'Quận 11',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '773',
    name: 'Quận 4',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '774',
    name: 'Quận 5',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '775',
    name: 'Quận 6',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '776',
    name: 'Quận 8',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '777',
    name: 'Quận Bình Tân',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '778',
    name: 'Quận 7',
    type: 'Quận',
    provinceId: '79',
  },
  {
    districtId: '783',
    name: 'Huyện Củ Chi',
    type: 'Huyện',
    provinceId: '79',
  },
  {
    districtId: '784',
    name: 'Huyện Hóc Môn',
    type: 'Huyện',
    provinceId: '79',
  },
  {
    districtId: '785',
    name: 'Huyện Bình Chánh',
    type: 'Huyện',
    provinceId: '79',
  },
  {
    districtId: '786',
    name: 'Huyện Nhà Bè',
    type: 'Huyện',
    provinceId: '79',
  },
  {
    districtId: '787',
    name: 'Huyện Cần Giờ',
    type: 'Huyện',
    provinceId: '79',
  },
  {
    districtId: '794',
    name: 'Thành phố Tân An',
    type: 'Thành phố',
    provinceId: '80',
  },
  {
    districtId: '795',
    name: 'Thị xã Kiến Tường',
    type: 'Thị xã',
    provinceId: '80',
  },
  {
    districtId: '796',
    name: 'Huyện Tân Hưng',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '797',
    name: 'Huyện Vĩnh Hưng',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '798',
    name: 'Huyện Mộc Hóa',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '799',
    name: 'Huyện Tân Thạnh',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '800',
    name: 'Huyện Thạnh Hóa',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '801',
    name: 'Huyện Đức Huệ',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '802',
    name: 'Huyện Đức Hòa',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '803',
    name: 'Huyện Bến Lức',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '804',
    name: 'Huyện Thủ Thừa',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '805',
    name: 'Huyện Tân Trụ',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '806',
    name: 'Huyện Cần Đước',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '807',
    name: 'Huyện Cần Giuộc',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '808',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '80',
  },
  {
    districtId: '815',
    name: 'Thành phố Mỹ Tho',
    type: 'Thành phố',
    provinceId: '82',
  },
  {
    districtId: '816',
    name: 'Thị xã Gò Công',
    type: 'Thị xã',
    provinceId: '82',
  },
  {
    districtId: '817',
    name: 'Thị xã Cai Lậy',
    type: 'Huyện',
    provinceId: '82',
  },
  {
    districtId: '818',
    name: 'Huyện Tân Phước',
    type: 'Huyện',
    provinceId: '82',
  },
  {
    districtId: '819',
    name: 'Huyện Cái Bè',
    type: 'Huyện',
    provinceId: '82',
  },
  {
    districtId: '820',
    name: 'Huyện Cai Lậy',
    type: 'Thị xã',
    provinceId: '82',
  },
  {
    districtId: '821',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '82',
  },
  {
    districtId: '822',
    name: 'Huyện Chợ Gạo',
    type: 'Huyện',
    provinceId: '82',
  },
  {
    districtId: '823',
    name: 'Huyện Gò Công Tây',
    type: 'Huyện',
    provinceId: '82',
  },
  {
    districtId: '824',
    name: 'Huyện Gò Công Đông',
    type: 'Huyện',
    provinceId: '82',
  },
  {
    districtId: '825',
    name: 'Huyện Tân Phú Đông',
    type: 'Huyện',
    provinceId: '82',
  },
  {
    districtId: '829',
    name: 'Thành phố Bến Tre',
    type: 'Thành phố',
    provinceId: '83',
  },
  {
    districtId: '831',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '83',
  },
  {
    districtId: '832',
    name: 'Huyện Chợ Lách',
    type: 'Huyện',
    provinceId: '83',
  },
  {
    districtId: '833',
    name: 'Huyện Mỏ Cày Nam',
    type: 'Huyện',
    provinceId: '83',
  },
  {
    districtId: '834',
    name: 'Huyện Giồng Trôm',
    type: 'Huyện',
    provinceId: '83',
  },
  {
    districtId: '835',
    name: 'Huyện Bình Đại',
    type: 'Huyện',
    provinceId: '83',
  },
  {
    districtId: '836',
    name: 'Huyện Ba Tri',
    type: 'Huyện',
    provinceId: '83',
  },
  {
    districtId: '837',
    name: 'Huyện Thạnh Phú',
    type: 'Huyện',
    provinceId: '83',
  },
  {
    districtId: '838',
    name: 'Huyện Mỏ Cày Bắc',
    type: 'Huyện',
    provinceId: '83',
  },
  {
    districtId: '842',
    name: 'Thành phố Trà Vinh',
    type: 'Thành phố',
    provinceId: '84',
  },
  {
    districtId: '844',
    name: 'Huyện Càng Long',
    type: 'Huyện',
    provinceId: '84',
  },
  {
    districtId: '845',
    name: 'Huyện Cầu Kè',
    type: 'Huyện',
    provinceId: '84',
  },
  {
    districtId: '846',
    name: 'Huyện Tiểu Cần',
    type: 'Huyện',
    provinceId: '84',
  },
  {
    districtId: '847',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '84',
  },
  {
    districtId: '848',
    name: 'Huyện Cầu Ngang',
    type: 'Huyện',
    provinceId: '84',
  },
  {
    districtId: '849',
    name: 'Huyện Trà Cú',
    type: 'Huyện',
    provinceId: '84',
  },
  {
    districtId: '850',
    name: 'Huyện Duyên Hải',
    type: 'Huyện',
    provinceId: '84',
  },
  {
    districtId: '851',
    name: 'Thị xã Duyên Hải',
    type: 'Thị xã',
    provinceId: '84',
  },
  {
    districtId: '855',
    name: 'Thành phố Vĩnh Long',
    type: 'Thành phố',
    provinceId: '86',
  },
  {
    districtId: '857',
    name: 'Huyện Long Hồ',
    type: 'Huyện',
    provinceId: '86',
  },
  {
    districtId: '858',
    name: 'Huyện Mang Thít',
    type: 'Huyện',
    provinceId: '86',
  },
  {
    districtId: '859',
    name: 'Huyện  Vũng Liêm',
    type: 'Huyện',
    provinceId: '86',
  },
  {
    districtId: '860',
    name: 'Huyện Tam Bình',
    type: 'Huyện',
    provinceId: '86',
  },
  {
    districtId: '861',
    name: 'Thị xã Bình Minh',
    type: 'Thị xã',
    provinceId: '86',
  },
  {
    districtId: '862',
    name: 'Huyện Trà Ôn',
    type: 'Huyện',
    provinceId: '86',
  },
  {
    districtId: '863',
    name: 'Huyện Bình Tân',
    type: 'Huyện',
    provinceId: '86',
  },
  {
    districtId: '866',
    name: 'Thành phố Cao Lãnh',
    type: 'Thành phố',
    provinceId: '87',
  },
  {
    districtId: '867',
    name: 'Thành phố Sa Đéc',
    type: 'Thành phố',
    provinceId: '87',
  },
  {
    districtId: '868',
    name: 'Thị xã Hồng Ngự',
    type: 'Thị xã',
    provinceId: '87',
  },
  {
    districtId: '869',
    name: 'Huyện Tân Hồng',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '870',
    name: 'Huyện Hồng Ngự',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '871',
    name: 'Huyện Tam Nông',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '872',
    name: 'Huyện Tháp Mười',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '873',
    name: 'Huyện Cao Lãnh',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '874',
    name: 'Huyện Thanh Bình',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '875',
    name: 'Huyện Lấp Vò',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '876',
    name: 'Huyện Lai Vung',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '877',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '87',
  },
  {
    districtId: '883',
    name: 'Thành phố Long Xuyên',
    type: 'Thành phố',
    provinceId: '89',
  },
  {
    districtId: '884',
    name: 'Thành phố Châu Đốc',
    type: 'Thành phố',
    provinceId: '89',
  },
  {
    districtId: '886',
    name: 'Huyện An Phú',
    type: 'Huyện',
    provinceId: '89',
  },
  {
    districtId: '887',
    name: 'Thị xã Tân Châu',
    type: 'Thị xã',
    provinceId: '89',
  },
  {
    districtId: '888',
    name: 'Huyện Phú Tân',
    type: 'Huyện',
    provinceId: '89',
  },
  {
    districtId: '889',
    name: 'Huyện Châu Phú',
    type: 'Huyện',
    provinceId: '89',
  },
  {
    districtId: '890',
    name: 'Huyện Tịnh Biên',
    type: 'Huyện',
    provinceId: '89',
  },
  {
    districtId: '891',
    name: 'Huyện Tri Tôn',
    type: 'Huyện',
    provinceId: '89',
  },
  {
    districtId: '892',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '89',
  },
  {
    districtId: '893',
    name: 'Huyện Chợ Mới',
    type: 'Huyện',
    provinceId: '89',
  },
  {
    districtId: '894',
    name: 'Huyện Thoại Sơn',
    type: 'Huyện',
    provinceId: '89',
  },
  {
    districtId: '899',
    name: 'Thành phố Rạch Giá',
    type: 'Thành phố',
    provinceId: '91',
  },
  {
    districtId: '900',
    name: 'Thị xã Hà Tiên',
    type: 'Thị xã',
    provinceId: '91',
  },
  {
    districtId: '902',
    name: 'Huyện Kiên Lương',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '903',
    name: 'Huyện Hòn Đất',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '904',
    name: 'Huyện Tân Hiệp',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '905',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '906',
    name: 'Huyện Giồng Riềng',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '907',
    name: 'Huyện Gò Quao',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '908',
    name: 'Huyện An Biên',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '909',
    name: 'Huyện An Minh',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '910',
    name: 'Huyện Vĩnh Thuận',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '911',
    name: 'Huyện Phú Quốc',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '912',
    name: 'Huyện Kiên Hải',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '913',
    name: 'Huyện U Minh Thượng',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '914',
    name: 'Huyện Giang Thành',
    type: 'Huyện',
    provinceId: '91',
  },
  {
    districtId: '916',
    name: 'Quận Ninh Kiều',
    type: 'Quận',
    provinceId: '92',
  },
  {
    districtId: '917',
    name: 'Quận Ô Môn',
    type: 'Quận',
    provinceId: '92',
  },
  {
    districtId: '918',
    name: 'Quận Bình Thuỷ',
    type: 'Quận',
    provinceId: '92',
  },
  {
    districtId: '919',
    name: 'Quận Cái Răng',
    type: 'Quận',
    provinceId: '92',
  },
  {
    districtId: '923',
    name: 'Quận Thốt Nốt',
    type: 'Quận',
    provinceId: '92',
  },
  {
    districtId: '924',
    name: 'Huyện Vĩnh Thạnh',
    type: 'Huyện',
    provinceId: '92',
  },
  {
    districtId: '925',
    name: 'Huyện Cờ Đỏ',
    type: 'Huyện',
    provinceId: '92',
  },
  {
    districtId: '926',
    name: 'Huyện Phong Điền',
    type: 'Huyện',
    provinceId: '92',
  },
  {
    districtId: '927',
    name: 'Huyện Thới Lai',
    type: 'Huyện',
    provinceId: '92',
  },
  {
    districtId: '930',
    name: 'Thành phố Vị Thanh',
    type: 'Thành phố',
    provinceId: '93',
  },
  {
    districtId: '931',
    name: 'Thị xã Ngã Bảy',
    type: 'Thị xã',
    provinceId: '93',
  },
  {
    districtId: '932',
    name: 'Huyện Châu Thành A',
    type: 'Huyện',
    provinceId: '93',
  },
  {
    districtId: '933',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '93',
  },
  {
    districtId: '934',
    name: 'Huyện Phụng Hiệp',
    type: 'Huyện',
    provinceId: '93',
  },
  {
    districtId: '935',
    name: 'Huyện Vị Thuỷ',
    type: 'Huyện',
    provinceId: '93',
  },
  {
    districtId: '936',
    name: 'Huyện Long Mỹ',
    type: 'Huyện',
    provinceId: '93',
  },
  {
    districtId: '937',
    name: 'Thị xã Long Mỹ',
    type: 'Thị xã',
    provinceId: '93',
  },
  {
    districtId: '941',
    name: 'Thành phố Sóc Trăng',
    type: 'Thành phố',
    provinceId: '94',
  },
  {
    districtId: '942',
    name: 'Huyện Châu Thành',
    type: 'Huyện',
    provinceId: '94',
  },
  {
    districtId: '943',
    name: 'Huyện Kế Sách',
    type: 'Huyện',
    provinceId: '94',
  },
  {
    districtId: '944',
    name: 'Huyện Mỹ Tú',
    type: 'Huyện',
    provinceId: '94',
  },
  {
    districtId: '945',
    name: 'Huyện Cù Lao Dung',
    type: 'Huyện',
    provinceId: '94',
  },
  {
    districtId: '946',
    name: 'Huyện Long Phú',
    type: 'Huyện',
    provinceId: '94',
  },
  {
    districtId: '947',
    name: 'Huyện Mỹ Xuyên',
    type: 'Huyện',
    provinceId: '94',
  },
  {
    districtId: '948',
    name: 'Thị xã Ngã Năm',
    type: 'Thị xã',
    provinceId: '94',
  },
  {
    districtId: '949',
    name: 'Huyện Thạnh Trị',
    type: 'Huyện',
    provinceId: '94',
  },
  {
    districtId: '950',
    name: 'Thị xã Vĩnh Châu',
    type: 'Thị xã',
    provinceId: '94',
  },
  {
    districtId: '951',
    name: 'Huyện Trần Đề',
    type: 'Huyện',
    provinceId: '94',
  },
  {
    districtId: '954',
    name: 'Thành phố Bạc Liêu',
    type: 'Thành phố',
    provinceId: '95',
  },
  {
    districtId: '956',
    name: 'Huyện Hồng Dân',
    type: 'Huyện',
    provinceId: '95',
  },
  {
    districtId: '957',
    name: 'Huyện Phước Long',
    type: 'Huyện',
    provinceId: '95',
  },
  {
    districtId: '958',
    name: 'Huyện Vĩnh Lợi',
    type: 'Huyện',
    provinceId: '95',
  },
  {
    districtId: '959',
    name: 'Thị xã Giá Rai',
    type: 'Thị xã',
    provinceId: '95',
  },
  {
    districtId: '960',
    name: 'Huyện Đông Hải',
    type: 'Huyện',
    provinceId: '95',
  },
  {
    districtId: '961',
    name: 'Huyện Hoà Bình',
    type: 'Huyện',
    provinceId: '95',
  },
  {
    districtId: '964',
    name: 'Thành phố Cà Mau',
    type: 'Thành phố',
    provinceId: '96',
  },
  {
    districtId: '966',
    name: 'Huyện U Minh',
    type: 'Huyện',
    provinceId: '96',
  },
  {
    districtId: '967',
    name: 'Huyện Thới Bình',
    type: 'Huyện',
    provinceId: '96',
  },
  {
    districtId: '968',
    name: 'Huyện Trần Văn Thời',
    type: 'Huyện',
    provinceId: '96',
  },
  {
    districtId: '969',
    name: 'Huyện Cái Nước',
    type: 'Huyện',
    provinceId: '96',
  },
  {
    districtId: '970',
    name: 'Huyện Đầm Dơi',
    type: 'Huyện',
    provinceId: '96',
  },
  {
    districtId: '971',
    name: 'Huyện Năm Căn',
    type: 'Huyện',
    provinceId: '96',
  },
  {
    districtId: '972',
    name: 'Huyện Phú Tân',
    type: 'Huyện',
    provinceId: '96',
  },
  {
    districtId: '973',
    name: 'Huyện Ngọc Hiển',
    type: 'Huyện',
    provinceId: '96',
  },
];

module.exports = { districts };
